routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/login');
});

Auth::routes(['register' => false]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/barang', App\Http\Controllers\Backend\ProductController::class, ['names' => 'product'])->except('show');
	Route::resource('/stok', App\Http\Controllers\Backend\StockController::class, ['names' => 'stock'])->except('edit', 'create', 'show');
	Route::resource('/satuan', App\Http\Controllers\Backend\UnitController::class, ['names' => 'unit'])->except('edit', 'create', 'show');
	Route::resource('/kategori', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('edit', 'create', 'show');
	Route::resource('/supplier', App\Http\Controllers\Backend\SupplierController::class, ['names' => 'supplier'])->except('edit', 'create', 'show');
	Route::resource('/customer', App\Http\Controllers\Backend\CustomerController::class, ['names' => 'customer'])->except('edit', 'create', 'show');
	Route::get('/kasir/receipt/{id}', [App\Http\Controllers\Backend\OrderController::class, 'receipt'])->name('order.receipt');
	Route::get('/kasir/transaksi/{id?}', [App\Http\Controllers\Backend\OrderController::class, 'show'])->name('order.show');
	// Route::put('/kasir/transaksi', [App\Http\Controllers\Backend\OrderController::class, 'transaction'])->name('order.transaction');
	Route::resource('/kasir', App\Http\Controllers\Backend\OrderController::class, ['names' => 'order'])->except('edit', 'create', 'show');

	Route::get('/report/stok', [App\Http\Controllers\Backend\ReportController::class, 'stockIndex'])->name('report.stock-index');
	Route::get('/report/penjualan', [App\Http\Controllers\Backend\ReportController::class, 'orderIndex'])->name('report.order-index');
	Route::get('/report/stok/data', [App\Http\Controllers\Backend\ReportController::class, 'stockShow'])->name('report.stock-show');
	Route::get('/report/penjualan/data', [App\Http\Controllers\Backend\ReportController::class, 'orderShow'])->name('report.order-show');
	Route::get('/report/barang/data', [App\Http\Controllers\Backend\ReportController::class, 'productShow'])->name('report.product-show');

	Route::resource('/hak-akses', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::put('/user/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');

	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->except('edit', 'create', 'show');
	Route::post('setting/password', [App\Http\Controllers\Backend\SettingController::class, 'password'])->name('setting.password');

	Route::get('/404', function(){
		return '404';
	})->name('error.404');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Haruncpi\LaravelIdGenerator\IdGenerator;
use App\Traits\Blameable;

class Order extends Model
{
    use HasFactory, Blameable;
    protected $primary   = 'id';
	public $incrementing = false;

	protected $guarded = [];

	public function createdBy()
	{
		return $this->belongsTo(User::class, 'created_by');
	}

	public function updatedBy()
	{
		return $this->belongsTo(User::class, 'updated_by');
	}

	public function product()
	{
		return $this->belongsTo(Product::class);
	}

	public function bill()
	{
		return $this->belongsTo(Bill::class);
	}

	public static function boot()
	{
		parent::boot();
		self::creating(function ($model) {
			$model->id = IdGenerator::generate(['table' => $model->getTable(), 'length' => 15, 'prefix' => 'ODR-'.date('ymd'), 'reset_on_prefix_change' => true]);
		});
	}
}

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Order;
use App\Models\Bill;
use Auth;

class OrderController extends Controller
{
	public function searchProduct(Request $request)
	{
		if (!empty($request->term)) {
			$q = '%'.strip_tags($request->term).'%';
			$products = Product::with('unit')->where('id', 'LIKE', $q)->orWhere('name', 'LIKE', $q)->take(10)->get();
			$products = $products->map(function($product){
				return [
					'value' 		=> $product->id.' '.$product->name,
					'label' 		=> $product->id.' '.$product->name,
					'id' 			=> $product->id,
					'name' 			=> $product->name,
					'thumbnail' 	=> $product->thumbnail,
					'selling_price' => $product->selling_price,
					'unit' 			=> $product->unit->name,
				];
			});
			return response()->json($products);
		}
	}

	public function stock(Request $request)
	{
		if (!empty($request->qty) && !empty($request->order_id) && !empty($request->id)) {
			$order = Order::whereHas('bill', function($q){
				return $q->where('status', 1);
			})->where('id', $request->order_id)->first();
			if ($order) {
				$max_stock = $order->product->current_stock;
				$qty = $request->qty > ($max_stock + $order->amount) ? ($max_stock + $order->amount) : $request->qty;
				if ($order->amount != $qty) {
					$total = ($qty - $order->amount) * $order->product->selling_price;
					$total = $total + $order->bill->pay;
					$order->bill()->update(['pay' => $total]);
				}
				$order->product()->update(['current_stock' => $order->product->current_stock + $order->amount - $qty]);
				$order->update(['amount' => $qty]);
			}
			return $this->data($request);
		}
	}

	public function destroy(Request $request)
	{
		if (!empty($request->order_id) && !empty($request->id)){
			$order = Order::whereHas('bill', function($q){
				return $q->where('status', 1);
			})->where('id', $request->order_id)->first();
			if ($order) {
				$total = $order->product->selling_price * $order->amount;
				$total = $order->bill->pay - $total;
				$order->bill()->update(['pay' => $total]);
				$order->product()->increment('current_stock', $order->amount);
				$order->delete();
			}
			return $this->data($request);
		}
	}

	public function discount(Request $request)
	{
		if (isset($request->id)){
			$bill = Bill::where(['id' => $request->id, 'status' => 1])->first();
			if ($bill) {
				$bill->update([
					'discount' => $request->discount ?? null
				]);
			}
			return $this->data($request);
		}	
	}

	public function paid(Request $request)
	{
		if (isset($request->id)){
			$bill = Bill::where(['id' => $request->id, 'status' => 1])->first();
			if ($bill) {
				$paid = $request->paid;
				if (!empty($paid)) {
					$paid = trim(str_ireplace(['rp.', '.'], '', $paid));
					$paid = (double)str_replace(',', '.', $paid);
					$paid = round($paid, 3);
				}
				$bill->update([
					'pay_money' => $paid
				]);
			}
			return $this->data($request);
		}	
	}

	public function data(Request $request)
	{
		$transaction = Bill::with('orders.product')->find($request->id);
		return view('backend.order.table-transaction', compact('transaction'));
	}

}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('permission:view kategori', ['only' => ['index']]);
        $this->middleware('permission:create kategori', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit kategori', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete kategori', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::orderByDesc('created_at')->get();
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:categories,name'
        ]);
        $category = Category::create(['name' => strip_tags($request->name)]);
        if ($category) {
            return back()->with('success','Input kategori barang berhasil');
        }
        return back()->with('error','Input kategori barang gagal, silakan coba kembali!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if ($category) {
            $request->validate([
                'name' => 'required|unique:categories,name,'.$category->id
            ]);
            $upd = $category->update(['name' => strip_tags($request->name)]);
            if ($upd) {
                return back()->with('success','Update kategori barang berhasil');
            }
            return back()->with('error','Update kategori barang gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if ($category) {
            $del = $category->delete();
            if ($del) {
                return back()->with('success','Hapus kategori barang berhasil');
            }
            return back()->with('error','Hapus kategori barang gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Customer;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view customer', ['only' => ['index']]);
        $this->middleware('permission:create customer', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit customer', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete customer', ['only' => ['destroy']]);
    }

    public function index()
    {
        $customers = Customer::orderByDesc('created_at')->get();
        return view('backend.customer.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id'      => 'required|numeric|unique:customers,id',
            'name'    => 'required',
            'phone'   => 'required|numeric|digits_between:8,15',
            'address' => 'required'
        ]);
        $payloads = removeHtmlTagsOfFields($request->except('_token'));
        $customer = Customer::create($payloads);
        if ($customer) {
            return back()->with('success','Input customer berhasil');
        }
        return back()->with('error','Input customer gagal, silakan coba kembali!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customer = Customer::find($id);
        if ($customer) {
            $request->validate([
                'id'      => 'required|numeric|unique:customers,id,'.$customer->id,
                'name'    => 'required',
                'phone'   => 'required|numeric|digits_between:8,15',
                'address' => 'required'
            ]);
            $payloads = removeHtmlTagsOfFields($request->except('_token', '_method'));
            $customer = $customer->update($payloads);
            if ($customer) {
                return back()->with('success','Update customer berhasil');
            }
            return back()->with('error','Update customer gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::find($id);
        if ($customer) {
            $del = $customer->delete();
            if ($del) {
                return back()->with('success','Hapus customer berhasil');
            }
            return back()->with('error','Hapus customer gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Bill;
use App\Models\Product;
use App\Models\Stock;
use App\Models\Order;
use DatePeriod;
use DateTime;
use DateInterval;

class DashboardController extends Controller
{
	public function index()
	{
		$bills 		   = Bill::whereMonth('created_at', date('m'))->get();
		$total_stock   = (int)Stock::sum('stock');
		$total_items   = Product::select('id')->count();
		$current_stock = (int)Product::sum('current_stock');
		$products      = Order::with('product')->selectRaw("product_id, SUM(amount) as total_amount")->groupBy('product_id')->orderByDesc('amount')->take(5)->get();
		$items         = Bill::whereBetween('created_at', [date('Y-m-d', strtotime('-1 week'))." 00:00:00", date('Y-m-d')." 23:59:59"])->get()->groupBy(function($item) {
			return date('d-m-Y', strtotime($item->created_at));
		});
		$periode = displayDates(date('Y-m-d', strtotime('-1 week')), date('Y-m-d'));
		$chartData['total_pay'] = [];
		$chartData['profit']    = [];
		foreach ($periode as $day) {
			if (isset($items[$day])) {
				$chartData['total_pay'][] = $items[$day]->sum('total_pay');
				$chartData['profit'][]    = $items[$day]->sum('profit');
			}else{
				$chartData['total_pay'][] = 0;				
				$chartData['profit'][]    = 0;				
			}
		}
		return view('backend.dashboard', compact('bills', 'total_items', 'total_stock', 'current_stock', 'products', 'chartData', 'periode'));
	}
}

resources/views/backend/order/index.blade.php
@extends('layouts.backend')
@section('css')
<link href="{{asset('vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection
@section('content')
<div class="card shadow mb-4">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Histori Transaksi</h6>
	</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th width="5%">No</th>
						<th>No Struk</th>
						<th>Customer</th>
						<th>Total Bayar</th>
						<th>Tanggal</th>
						<th>Status</th>
						<th width="10%"><center>#</center></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th width="5%">No</th>
						<th>No Struk</th>
						<th>Customer</th>
						<th>Total Bayar</th>
						<th>Tanggal</th>
						<th>Status</th>
						@canany(['create transaksi', 'delete transaksi'])
						<th width="10%"><center>#</center></th>
						@endcan
					</tr>
				</tfoot>
				<tbody>
					@foreach($bills as $bill)
					<tr>
						<td>{{$loop->iteration}}</td>
						<td>{{$bill->id}}</td>
						<td>{{empty($bill->customer->name) ? 'Umum' : ucwords($bill->customer->name)}}</td>
						<td>{!!empty($bill->total_pay) ? '<center>-</center>' : 'Rp. '.rupiah($bill->total_pay)!!}</td>
						<td>{{date('d/m/y H:i', strtotime($bill->created_at))}}</td>
						<td>
							<label class="badge badge-{{$bill->status == 1 ? 'primary' : 'success'}}">{{$bill->status == 1 ? 'Draft' : 'Lunas'}}</label>
						</td>
						@canany(['create transaksi', 'delete transaksi'])
						<td>
							<center>
								@can('create transaksi')
								<a href="{{route('dashboard.order.show', $bill->id)}}" class="btn btn-sm btn-primary"><i class="fas fa-folder-open"></i></a>
								@endcan
								@can('delete transaksi')
								@if($bill->status == 1)
								<a data-toggle="modal" onclick="modalDelete(this)" data-id="{{$bill->id}}" data-target="#modal-delete" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
								@endif
								@endcan
							</center>
						</td>
						@endcan
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>

@can('delete transaksi')
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('DELETE')
				<div class="modal-header bg-danger">
					<h5 class="modal-title text-white">Hapus Transaksi Item</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Apakah ingin menghapus transaksi dengan nomor struk <span id="modal-delete-name"></span> ?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-danger">Delete</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan
@endsection
@push('js')
<script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('#dataTable').DataTable();
	});
	
	@can('delete transaksi')
	function modalDelete(self)
	{
		var modal = $('#modal-delete');
		var id 	  = $(self).data('id');
		var url   = '{{route('dashboard.order.destroy', ':id')}}';
		url = url.replace(':id', id);
		$('#modal-delete-name').html('<b>'+id+'</b>');
		modal.find('form').attr('action', url);
	}
	@endcan
</script>
@endpush

resources/views/backend/order/receipt.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Struk Belanjaan</title>
	<style type="text/css">
		.title{
			text-align: center;
		}
		.dashed{
			border-top: 1px dashed #000;
		}
		.mt-none{
			margin-top: unset;
		}
		.mb-none{
			margin-bottom: unset;
		}
		table{
			width: 100%;
		}
		.solid{
			border-top: 2px solid #000;
		}
		@media print{
			button{
				display: none;
			}
		}
	</style>
</head>
<body>
	<h4 class="title mb-none">Laramart App</h4>
	<p class="title mt-none">Jln Panunggulan no. 36B Indramayu</p>
	<hr class="dashed">
	<table border="0">
		<tr>
			<td>{{date('d/m/y H:i')}}</td>
			<td></td>
			<td align="right">Cashier</td>
			<td>:</td>
			<td align="right">{{$bill->createdBy->name ?? 'Admin'}}</td>
		</tr>
		<tr>
			<td>{{$bill->id}}</td>
			<td></td>
			<td align="right">Customer</td>
			<td>:</td>
			<td align="right">{{$bill->customer->name ?? 'Umum'}}</td>
		</tr>
		<tr>
			<td colspan="5"><div class="solid"></div></td>
		</tr>
		@foreach($bill->orders as $order)
		<tr>
			<td>{{$order->product->name}}</td>
			<td align="right">{{$order->amount}}</td>
			<td align="right">Rp. {{rupiah($order->product->selling_price)}}</td>
			<td></td>
			<td align="right">Rp. {{rupiah($order->product->selling_price * $order->amount)}}</td>
		</tr>
		@endforeach
		<tr>
			<td colspan="5"><div class="dashed"></div></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td align="right">Sub Total</td>
			<td></td>
			<td align="right">Rp. {{rupiah($bill->pay)}}</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td class="dashed" align="right">Potongan</td>
			<td class="dashed"></td>
			<td align="right" class="dashed">Rp. {{rupiah($bill->cutting_price)}}</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td class="dashed" align="right">Total</td>
			<td class="dashed"></td>
			<td align="right" class="dashed">Rp. {{rupiah($bill->total_pay)}}</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td class="dashed" align="right">Bayar</td>
			<td class="dashed"></td>
			<td align="right" class="dashed">Rp. {{rupiah($bill->pay_money)}}</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td class="dashed" align="right">Kembali</td>
			<td class="dashed"></td>
			<td align="right" class="dashed">Rp. {{rupiah($bill->pay_money - $bill->total_pay)}}</td>
		</tr>
	</table>
	<hr class="dashed">
	<h4 class="title mb-none">Terima Kasih</h4>
	<button type="button" onclick="window.print()">Print</button>
</body>
</html>

resources/views/backend/order/table-transaction.blade.php
@php
$pay       = $transaction->pay ?? null;
$discount  = $transaction->discount ?? null;
$cutting_price = $pay * $discount / 100;
$total     = $pay - $cutting_price;
$pay_money = $transaction->pay_money ?? null;
$cash_back = empty($pay_money) ? null : $pay_money - $total;
$disabled  = '';
if (isset($transaction->status)) {
	$disabled = $transaction->status == 1 ? '' : 'disabled';
}
$transactionId = empty($transaction->id) ? 'null' : $transaction->id;
@endphp
<form method="POST" action="{{$cash_back < 0 ? '' : route('dashboard.order.update', $transactionId)}}" id="form-transaction">
	@csrf
	@method('PUT')
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0" data-status="{{$transaction->status ?? null}}">
				<thead>
					<tr>
						<th width="5%">No</th>
						<th>Kode</th>
						<th>Nama Barang</th>
						<th>Harga (Rp.)</th>
						<th>Qty</th>
						<th width="30%">Total</th>
						<th width="5%"><center>#</center></th>
					</tr>
				</thead>
				<tbody>
					@if(!empty($transaction->orders))
					@forelse($transaction->orders as $order)
					<tr data-orderid="{{$order->id}}">
						<td>{{$loop->iteration}}</td>
						<td>{{$order->product->id}}</td>
						<td>{{$order->product->name}}</td>
						<td>{{rupiah($order->product->selling_price)}}</td>
						<td>
							<input type="number" value="{{$order->amount}}" min="1" max="{{$order->product->current_stock + $order->amount}}" class="form-control d-inline-block" style="max-width: 60px" onchange="setQty(this)" {{$disabled}}>
							<div class="clearfix"></div>
							<small>Stok tersedia : {{$order->product->current_stock}}</small>
						</td>
						<td><span id="qtyTotal" data-price="{{$order->product->selling_price}}" data-total="{{$order->product->selling_price}}">{{rupiah($order->amount * $order->product->selling_price)}}</span></td>
						<td>
							@if($transaction->status == 1)
							<button class="btn btn-sm btn-danger" data-name="{{$order->product->name}}" type="button" onclick="modalDelete(this)"><i class="fa fa-trash"></i></button>
							@endif
						</td>
					</tr>
					@empty
					<tr class="empty">
						<td colspan="7"><center><i>kosong</i></center></td>
					</tr>
					@endforelse
					@else
					<tr class="empty">
						<td colspan="7"><center><i>kosong</i></center></td>
					</tr>
					@endif
				</tbody>
				<tfoot>
					<tr>
						<th colspan="4"></th>
						<th>Sub Total</th>
						<th><input type="text" class="form-control" value="Rp. {{rupiah($pay)}}" data-total="{{$pay}}" disabled></th>
						<th></th>
					</tr>
					<tr>
						<th colspan="4"></th>
						<th>Diskon</th>
						<th>
							<div class="input-group mb-3">
								<input type="number" min="0" max="100" value="{{$discount}}" name="discount" onchange="setDiscount(this.value)" class="form-control" placeholder="diskon dalam %" {{$disabled}}>
								<div class="input-group-append">
									<span class="input-group-text" id="basic-addon2">%</span>
								</div>
							</div>
						</th>
						<th></th>
					</tr>
					<tr>
						<th colspan="4"></th>
						<th>Potongan Diskon</th>
						<th>
							<div class="input-group mb-3">
								<div class="input-group-append">
									<span class="input-group-text" id="basic-addon2">Rp. </span>
								</div>
								<input type="text" class="form-control" id="potongan" value="{{rupiah($cutting_price) }}" disabled>
							</div>
						</th>
						<th></th>
					</tr>
					<tr>
						<th colspan="4"></th>
						<th>Total</th>
						<th><input type="text" class="form-control" value="Rp. {{rupiah($total)}}" disabled></th>
						<th></th>
					</tr>
					<tr>
						<th colspan="4"></th>
						<th>Bayar</th>
						<th><input type="text" name="bill" class="form-control" onkeyup="setRupiahBayar(this)" onchange="setPaid(this)" value="{{empty($pay_money) ? null : 'Rp. '.rupiah($pay_money)}}" {{empty($disabled) ? 'required' : $disabled}}></th>
						<th></th>
					</tr>
					<tr>
						<th colspan="4"></th>
						<th>Kembalian</th>
						<th><input type="text" name="cash_back" class="form-control{{$cash_back < 0 ? ' b-red' : ''}}" value="{{empty($cash_back) ? null : 'Rp. '.rupiah($cash_back)}}" disabled></th>
						<th></th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
	<div class="card-footer" style="display: flow-root">
		@if(isset($transaction->status))
		@if($transaction->status == 1)
		<input type="hidden" name="customer_id">
		<button type="submit" class="btn btn-primary float-right" {{$cash_back < 0 ? 'disabled' : ''}}><i class="fas fa-cash-register"></i> Transaksi</button>
		@else
		<div class="float-right">	
			<a class="btn btn-danger" href="{{route('dashboard.order.show')}}"><i class="fas fa-cash-register"></i> Transaksi Baru</a>
			&nbsp;&nbsp;&nbsp;
			<button type="button" class="btn btn-success" onclick="window.open('{{route('dashboard.order.receipt', $transaction->id)}}','mywindow','width=400px,height=600px,left=300px;top=100px;')"><i class="fa fa-print"></i> Cetak Struk</button>
		</div>
		@endif
		@else
		<a class="btn btn-danger" href="{{url()->previous()}}">Back</a>
		@endif
	</div>
</form>