routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/login');
});

Auth::routes(['register' => false]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/barang', App\Http\Controllers\Backend\ProductController::class, ['names' => 'product'])->except('show');
	Route::resource('/stok', App\Http\Controllers\Backend\StockController::class, ['names' => 'stock'])->except('edit', 'create', 'show');
	Route::resource('/satuan', App\Http\Controllers\Backend\UnitController::class, ['names' => 'unit'])->except('edit', 'create', 'show');
	Route::resource('/kategori', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('edit', 'create', 'show');
	Route::resource('/supplier', App\Http\Controllers\Backend\SupplierController::class, ['names' => 'supplier'])->except('edit', 'create', 'show');
	Route::resource('/customer', App\Http\Controllers\Backend\CustomerController::class, ['names' => 'customer'])->except('edit', 'create', 'show');
	Route::get('/kasir/receipt/{id}', [App\Http\Controllers\Backend\OrderController::class, 'receipt'])->name('order.receipt');
	Route::get('/kasir/transaksi/{id?}', [App\Http\Controllers\Backend\OrderController::class, 'show'])->name('order.show');
	// Route::put('/kasir/transaksi', [App\Http\Controllers\Backend\OrderController::class, 'transaction'])->name('order.transaction');
	Route::resource('/kasir', App\Http\Controllers\Backend\OrderController::class, ['names' => 'order'])->except('edit', 'create', 'show');

	Route::get('/report/stok', [App\Http\Controllers\Backend\ReportController::class, 'stockIndex'])->name('report.stock-index');
	Route::get('/report/penjualan', [App\Http\Controllers\Backend\ReportController::class, 'orderIndex'])->name('report.order-index');
	Route::get('/report/stok/data', [App\Http\Controllers\Backend\ReportController::class, 'stockShow'])->name('report.stock-show');
	Route::get('/report/penjualan/data', [App\Http\Controllers\Backend\ReportController::class, 'orderShow'])->name('report.order-show');
	Route::get('/report/barang/data', [App\Http\Controllers\Backend\ReportController::class, 'productShow'])->name('report.product-show');

	Route::resource('/hak-akses', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::put('/user/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');

	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->except('edit', 'create', 'show');
	Route::post('setting/password', [App\Http\Controllers\Backend\SettingController::class, 'password'])->name('setting.password');

	Route::get('/404', function(){
		return '404';
	})->name('error.404');
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Haruncpi\LaravelIdGenerator\IdGenerator;
use App\Traits\Blameable;

class Supplier extends Model
{
    use HasFactory, Blameable;
    protected $primary   = 'id';
	public $incrementing = false;

	protected $guarded = [];

	public function createdBy()
	{
		return $this->belongsTo(User::class, 'created_by');
	}

	public function updatedBy()
	{
		return $this->belongsTo(User::class, 'updated_by');
	}

	public function stocks()
	{
		return $this->hasMany(Stock::class);
	}

	public static function boot()
	{
		parent::boot();
		self::creating(function ($model) {
			$model->id = IdGenerator::generate(['table' => $model->getTable(), 'length' => 15, 'prefix' => 'SUP-'.date('ymd'), 'reset_on_prefix_change' => true]);
		});
	}
}

app/Http/Controllers/Api/SupplierController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Supplier;

class SupplierController extends Controller
{
    public function edit($id)
	{
		$supplier = Supplier::select('id', 'name', 'phone', 'email', 'address')->find($id);
		if ($supplier) {
			return response()->json(['status' => 200, 'message' => 'success', 'data' => $supplier]);
		}
		return response()->json(['status' => 400, 'message' => 'failed']);
	}
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('permission:view kategori', ['only' => ['index']]);
        $this->middleware('permission:create kategori', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit kategori', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete kategori', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::orderByDesc('created_at')->get();
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:categories,name'
        ]);
        $category = Category::create(['name' => strip_tags($request->name)]);
        if ($category) {
            return back()->with('success','Input kategori barang berhasil');
        }
        return back()->with('error','Input kategori barang gagal, silakan coba kembali!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if ($category) {
            $request->validate([
                'name' => 'required|unique:categories,name,'.$category->id
            ]);
            $upd = $category->update(['name' => strip_tags($request->name)]);
            if ($upd) {
                return back()->with('success','Update kategori barang berhasil');
            }
            return back()->with('error','Update kategori barang gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if ($category) {
            $del = $category->delete();
            if ($del) {
                return back()->with('success','Hapus kategori barang berhasil');
            }
            return back()->with('error','Hapus kategori barang gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Customer;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view customer', ['only' => ['index']]);
        $this->middleware('permission:create customer', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit customer', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete customer', ['only' => ['destroy']]);
    }

    public function index()
    {
        $customers = Customer::orderByDesc('created_at')->get();
        return view('backend.customer.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id'      => 'required|numeric|unique:customers,id',
            'name'    => 'required',
            'phone'   => 'required|numeric|digits_between:8,15',
            'address' => 'required'
        ]);
        $payloads = removeHtmlTagsOfFields($request->except('_token'));
        $customer = Customer::create($payloads);
        if ($customer) {
            return back()->with('success','Input customer berhasil');
        }
        return back()->with('error','Input customer gagal, silakan coba kembali!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customer = Customer::find($id);
        if ($customer) {
            $request->validate([
                'id'      => 'required|numeric|unique:customers,id,'.$customer->id,
                'name'    => 'required',
                'phone'   => 'required|numeric|digits_between:8,15',
                'address' => 'required'
            ]);
            $payloads = removeHtmlTagsOfFields($request->except('_token', '_method'));
            $customer = $customer->update($payloads);
            if ($customer) {
                return back()->with('success','Update customer berhasil');
            }
            return back()->with('error','Update customer gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::find($id);
        if ($customer) {
            $del = $customer->delete();
            if ($del) {
                return back()->with('success','Hapus customer berhasil');
            }
            return back()->with('error','Hapus customer gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Bill;
use App\Models\Product;
use App\Models\Stock;
use App\Models\Order;
use DatePeriod;
use DateTime;
use DateInterval;

class DashboardController extends Controller
{
	public function index()
	{
		$bills 		   = Bill::whereMonth('created_at', date('m'))->get();
		$total_stock   = (int)Stock::sum('stock');
		$total_items   = Product::select('id')->count();
		$current_stock = (int)Product::sum('current_stock');
		$products      = Order::with('product')->selectRaw("product_id, SUM(amount) as total_amount")->groupBy('product_id')->orderByDesc('amount')->take(5)->get();
		$items         = Bill::whereBetween('created_at', [date('Y-m-d', strtotime('-1 week'))." 00:00:00", date('Y-m-d')." 23:59:59"])->get()->groupBy(function($item) {
			return date('d-m-Y', strtotime($item->created_at));
		});
		$periode = displayDates(date('Y-m-d', strtotime('-1 week')), date('Y-m-d'));
		$chartData['total_pay'] = [];
		$chartData['profit']    = [];
		foreach ($periode as $day) {
			if (isset($items[$day])) {
				$chartData['total_pay'][] = $items[$day]->sum('total_pay');
				$chartData['profit'][]    = $items[$day]->sum('profit');
			}else{
				$chartData['total_pay'][] = 0;				
				$chartData['profit'][]    = 0;				
			}
		}
		return view('backend.dashboard', compact('bills', 'total_items', 'total_stock', 'current_stock', 'products', 'chartData', 'periode'));
	}
}

app/Http/Controllers/Backend/ReportController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Models\Stock;
use App\Models\Customer;
use App\Models\Bill;

class ReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:view laporan stok', ['only' => ['stockIndex', 'stockShow']]);
        $this->middleware('permission:view laporan transaksi', ['only' => ['orderIndex', 'orderShow']]);
        $this->middleware('permission:view laporan barang', ['only' => ['productShow']]);
    }

    public function stockIndex()
    {
    	$products = Product::orderBy('name')->get();
    	$categories = Category::orderBy('name')->get();
    	return view('backend.report.stock.index', compact('products', 'categories'));
    }

    public function stockShow(Request $request)
    {
    	$stocks = Stock::with('product.category', 'product.unit', 'createdBy', 'supplier')->whereHas('product', function($product) use ($request){
    		return $product->whereHas('category', function($category) use ($request){
    			return $category->whereIn('id', $request->categories);
    		})->where('id', 'LIKE', $request->product);
    	})->whereBetween('created_at', [$request->fdate." 00:00:00", $request->tdate." 23:59:59"])->orderBy('created_at')->get();
    	return view('backend.report.stock.show', compact('stocks'));
    }

    public function orderIndex()
    {
    	$customers = Customer::orderBy('name')->get();
    	return view('backend.report.order.index', compact('customers'));
    }

    public function orderShow(Request $request)
    {
        // dd($request->all());
    	$bills = Bill::with('orders.product.unit')->where('status', 2)->whereBetween('created_at', [$request->fdate." 00:00:00", $request->tdate." 23:59:59"]);
    	if (!empty($request->minpay)) {
    		$bills = $bills->where('total_pay', '>=', $request->minpay);
    	}
    	if (!empty($request->maxpay)) {
    		$bills = $bills->where('total_pay', '<=', $request->maxpay);
    	}
        if ($request->customer != '%') {
            $bills = $bills->where('customer_id', $request->customer);
        }
    	$bills = $bills->get();
    	$tpay  = $tprofit = $tdiscount = 0;
    	return view('backend.report.order.show', compact('bills', 'request', 'tpay', 'tprofit', 'tdiscount'));
    }

    public function productShow()
    {
    	$products = Product::with('unit', 'stocks', 'orders.bill')->orderBy('name')->get();
    	return view('backend.report.product.show', compact('products'));
    }
}

resources/views/backend/supplier/index.blade.php
@extends('layouts.backend')
@section('css')
<link href="{{asset('vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection
@section('content')
<div class="card shadow mb-4">
	<div class="card-header py-3">
		@can('create supplier')
		<a data-target="#modal-create" data-toggle="modal" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Supplier Barang</a>
		@endcan
		<h6 class="m-0 font-weight-bold text-primary float-right">List Tabel Supplier Barang</h6>
	</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th width="5%">No</th>
						<th>Nama</th>
						<th>No HP</th>
						<th>Email</th>
						<th>Alamat</th>
						@canany(['delete supplier', 'edit supplier'])
						<th width="10%"><center>#</center></th>
						@endcan
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th width="5%">No</th>
						<th>Nama</th>
						<th>No HP</th>
						<th>Email</th>
						<th>Alamat</th>
						@canany(['delete supplier', 'edit supplier'])
						<th width="10%"><center>#</center></th>
						@endcan
					</tr>
				</tfoot>
				<tbody>
					@foreach($suppliers as $supplier)
					<tr>
						<td>{{$loop->iteration}}</td>
						<td>{{$supplier->name}}</td>
						<td>{{$supplier->phone}}</td>
						<td>{{$supplier->email}}</td>
						<td>{{$supplier->address}}</td>
						@canany(['delete supplier', 'edit supplier'])
						<td>
							<center>
								@can('edit supplier')
								<a onclick="modalEdit(this)" data-id="{{$supplier->id}}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a>
								@endcan
								@can('delete supplier')
								<a data-toggle="modal" onclick="modalDelete(this)" data-id="{{$supplier->id}}" data-name="{{$supplier->name}}" data-target="#modal-delete" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
								@endcan
							</center>
						</td>
						@endcan
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>

@can('create supplier')
<div class="modal fade" id="modal-create" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="{{route('dashboard.supplier.store')}}" method="POST">
				@csrf
				<div class="modal-header bg-primary">
					<h5 class="modal-title text-white">Tambah Supplier Barang</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Nama Supplier</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>No HP</label>
						<input type="text" name="phone" minlength="8" maxlength="15" onkeypress="return isNumberKey(event)" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Alamat</label>
						<textarea class="form-control" name="address" rows="3" required></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('edit supplier')
<div class="modal fade" id="modal-edit" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('PUT')
				<div class="modal-header bg-primary">
					<h5 class="modal-title text-white">Edit Supplier Barang</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Nama Supplier</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>No HP</label>
						<input type="text" name="phone" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Alamat</label>
						<textarea class="form-control" name="address" rows="3" required></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Edit</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('delete supplier')
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('DELETE')
				<div class="modal-header bg-danger">
					<h5 class="modal-title text-white">Hapus Supplier Barang</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Apakah ingin menghapus supplier <span id="modal-delete-name"></span> ?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-danger">Delete</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan
@endsection
@push('js')
<script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('#dataTable').DataTable();
	});

	function isNumberKey(evt){
		var charCode = (evt.which) ? evt.which : evt.keyCode;
		if (charCode > 31 && (charCode < 48 || charCode > 57))
			return false;
		return true;
	}

	@can('delete supplier')
	function modalDelete(self)
	{
		var modal = $('#modal-delete');
		var id 	  = $(self).data('id');
		var name  = $(self).data('name');
		var url   = '{{route('dashboard.supplier.destroy', ':id')}}';
		url = url.replace(':id', id);
		$('#modal-delete-name').html('<b>'+name+'</b>');
		modal.find('form').attr('action', url);
	}
	@endcan

	@can('edit supplier')
	function modalEdit(self)
	{
		var modal  = $('#modal-edit');
		var id     = $(self).data('id');
		var apiUrl = '{{route('api.supplier.edit', ':id')}}';
		apiUrl     = apiUrl.replace(':id', id)
		$.get(apiUrl, function(response){
			if (response.status === 200) {
				var data = response.data;
				modal.find('input[name="name"]').val(data.name);
				modal.find('input[name="phone"]').val(data.phone);
				modal.find('input[name="email"]').val(data.email);
				modal.find('textarea[name="address"]').val(data.address);
			}
		});

		var url   = '{{route('dashboard.supplier.update', ':id')}}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.modal('show');
	}
	@endcan
</script>
@endpush