routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('/login');
});

Auth::routes(['register' => false]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/barang', App\Http\Controllers\Backend\ProductController::class, ['names' => 'product'])->except('show');
	Route::resource('/stok', App\Http\Controllers\Backend\StockController::class, ['names' => 'stock'])->except('edit', 'create', 'show');
	Route::resource('/satuan', App\Http\Controllers\Backend\UnitController::class, ['names' => 'unit'])->except('edit', 'create', 'show');
	Route::resource('/kategori', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('edit', 'create', 'show');
	Route::resource('/supplier', App\Http\Controllers\Backend\SupplierController::class, ['names' => 'supplier'])->except('edit', 'create', 'show');
	Route::resource('/customer', App\Http\Controllers\Backend\CustomerController::class, ['names' => 'customer'])->except('edit', 'create', 'show');
	Route::get('/kasir/receipt/{id}', [App\Http\Controllers\Backend\OrderController::class, 'receipt'])->name('order.receipt');
	Route::get('/kasir/transaksi/{id?}', [App\Http\Controllers\Backend\OrderController::class, 'show'])->name('order.show');
	// Route::put('/kasir/transaksi', [App\Http\Controllers\Backend\OrderController::class, 'transaction'])->name('order.transaction');
	Route::resource('/kasir', App\Http\Controllers\Backend\OrderController::class, ['names' => 'order'])->except('edit', 'create', 'show');

	Route::get('/report/stok', [App\Http\Controllers\Backend\ReportController::class, 'stockIndex'])->name('report.stock-index');
	Route::get('/report/penjualan', [App\Http\Controllers\Backend\ReportController::class, 'orderIndex'])->name('report.order-index');
	Route::get('/report/stok/data', [App\Http\Controllers\Backend\ReportController::class, 'stockShow'])->name('report.stock-show');
	Route::get('/report/penjualan/data', [App\Http\Controllers\Backend\ReportController::class, 'orderShow'])->name('report.order-show');
	Route::get('/report/barang/data', [App\Http\Controllers\Backend\ReportController::class, 'productShow'])->name('report.product-show');

	Route::resource('/hak-akses', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::put('/user/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');

	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->except('edit', 'create', 'show');
	Route::post('setting/password', [App\Http\Controllers\Backend\SettingController::class, 'password'])->name('setting.password');

	Route::get('/404', function(){
		return '404';
	})->name('error.404');
});

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('permission:view kategori', ['only' => ['index']]);
        $this->middleware('permission:create kategori', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit kategori', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete kategori', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::orderByDesc('created_at')->get();
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:categories,name'
        ]);
        $category = Category::create(['name' => strip_tags($request->name)]);
        if ($category) {
            return back()->with('success','Input kategori barang berhasil');
        }
        return back()->with('error','Input kategori barang gagal, silakan coba kembali!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if ($category) {
            $request->validate([
                'name' => 'required|unique:categories,name,'.$category->id
            ]);
            $upd = $category->update(['name' => strip_tags($request->name)]);
            if ($upd) {
                return back()->with('success','Update kategori barang berhasil');
            }
            return back()->with('error','Update kategori barang gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if ($category) {
            $del = $category->delete();
            if ($del) {
                return back()->with('success','Hapus kategori barang berhasil');
            }
            return back()->with('error','Hapus kategori barang gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Customer;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view customer', ['only' => ['index']]);
        $this->middleware('permission:create customer', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit customer', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete customer', ['only' => ['destroy']]);
    }

    public function index()
    {
        $customers = Customer::orderByDesc('created_at')->get();
        return view('backend.customer.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id'      => 'required|numeric|unique:customers,id',
            'name'    => 'required',
            'phone'   => 'required|numeric|digits_between:8,15',
            'address' => 'required'
        ]);
        $payloads = removeHtmlTagsOfFields($request->except('_token'));
        $customer = Customer::create($payloads);
        if ($customer) {
            return back()->with('success','Input customer berhasil');
        }
        return back()->with('error','Input customer gagal, silakan coba kembali!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customer = Customer::find($id);
        if ($customer) {
            $request->validate([
                'id'      => 'required|numeric|unique:customers,id,'.$customer->id,
                'name'    => 'required',
                'phone'   => 'required|numeric|digits_between:8,15',
                'address' => 'required'
            ]);
            $payloads = removeHtmlTagsOfFields($request->except('_token', '_method'));
            $customer = $customer->update($payloads);
            if ($customer) {
                return back()->with('success','Update customer berhasil');
            }
            return back()->with('error','Update customer gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::find($id);
        if ($customer) {
            $del = $customer->delete();
            if ($del) {
                return back()->with('success','Hapus customer berhasil');
            }
            return back()->with('error','Hapus customer gagal, silakan coba kembali!');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Bill;
use App\Models\Product;
use App\Models\Stock;
use App\Models\Order;
use DatePeriod;
use DateTime;
use DateInterval;

class DashboardController extends Controller
{
	public function index()
	{
		$bills 		   = Bill::whereMonth('created_at', date('m'))->get();
		$total_stock   = (int)Stock::sum('stock');
		$total_items   = Product::select('id')->count();
		$current_stock = (int)Product::sum('current_stock');
		$products      = Order::with('product')->selectRaw("product_id, SUM(amount) as total_amount")->groupBy('product_id')->orderByDesc('amount')->take(5)->get();
		$items         = Bill::whereBetween('created_at', [date('Y-m-d', strtotime('-1 week'))." 00:00:00", date('Y-m-d')." 23:59:59"])->get()->groupBy(function($item) {
			return date('d-m-Y', strtotime($item->created_at));
		});
		$periode = displayDates(date('Y-m-d', strtotime('-1 week')), date('Y-m-d'));
		$chartData['total_pay'] = [];
		$chartData['profit']    = [];
		foreach ($periode as $day) {
			if (isset($items[$day])) {
				$chartData['total_pay'][] = $items[$day]->sum('total_pay');
				$chartData['profit'][]    = $items[$day]->sum('profit');
			}else{
				$chartData['total_pay'][] = 0;				
				$chartData['profit'][]    = 0;				
			}
		}
		return view('backend.dashboard', compact('bills', 'total_items', 'total_stock', 'current_stock', 'products', 'chartData', 'periode'));
	}
}

app/Http/Controllers/Backend/ReportController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Models\Stock;
use App\Models\Customer;
use App\Models\Bill;

class ReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:view laporan stok', ['only' => ['stockIndex', 'stockShow']]);
        $this->middleware('permission:view laporan transaksi', ['only' => ['orderIndex', 'orderShow']]);
        $this->middleware('permission:view laporan barang', ['only' => ['productShow']]);
    }

    public function stockIndex()
    {
    	$products = Product::orderBy('name')->get();
    	$categories = Category::orderBy('name')->get();
    	return view('backend.report.stock.index', compact('products', 'categories'));
    }

    public function stockShow(Request $request)
    {
    	$stocks = Stock::with('product.category', 'product.unit', 'createdBy', 'supplier')->whereHas('product', function($product) use ($request){
    		return $product->whereHas('category', function($category) use ($request){
    			return $category->whereIn('id', $request->categories);
    		})->where('id', 'LIKE', $request->product);
    	})->whereBetween('created_at', [$request->fdate." 00:00:00", $request->tdate." 23:59:59"])->orderBy('created_at')->get();
    	return view('backend.report.stock.show', compact('stocks'));
    }

    public function orderIndex()
    {
    	$customers = Customer::orderBy('name')->get();
    	return view('backend.report.order.index', compact('customers'));
    }

    public function orderShow(Request $request)
    {
        // dd($request->all());
    	$bills = Bill::with('orders.product.unit')->where('status', 2)->whereBetween('created_at', [$request->fdate." 00:00:00", $request->tdate." 23:59:59"]);
    	if (!empty($request->minpay)) {
    		$bills = $bills->where('total_pay', '>=', $request->minpay);
    	}
    	if (!empty($request->maxpay)) {
    		$bills = $bills->where('total_pay', '<=', $request->maxpay);
    	}
        if ($request->customer != '%') {
            $bills = $bills->where('customer_id', $request->customer);
        }
    	$bills = $bills->get();
    	$tpay  = $tprofit = $tdiscount = 0;
    	return view('backend.report.order.show', compact('bills', 'request', 'tpay', 'tprofit', 'tdiscount'));
    }

    public function productShow()
    {
    	$products = Product::with('unit', 'stocks', 'orders.bill')->orderBy('name')->get();
    	return view('backend.report.product.show', compact('products'));
    }
}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use Hash;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.setting.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function password(Request $request)
    {
        $request->validate([
            'cpassword' => 'required',
            'npassword' => 'required|same:rpassword|min:6',
            'rpassword' => 'required|min:6',
        ]);
        $user = Auth::user();
        if (Hash::check($request->cpassword, $user->password)) {
            $upd = $user->update(['password' => bcrypt($request->npassword)]);
            if ($upd) {
                return redirect()->back()->with('success', 'password '.$user->name.' berhasil di ganti');          
            }
            return redirect()->back()->with('error', 'Gagal, silakan coba kembali');
        }else{
            return redirect()->back()->with('error', 'password lama tidak cocok');
        }
    }
}

resources/views/backend/user/index.blade.php
@extends('layouts.backend')
@section('title', 'AdminLTE 3 | User Index')
@section('css')
<link href="{{asset('vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
<link href="{{asset('vendor/select2/select2.min.css')}}" rel="stylesheet">
<style type="text/css">
	#tbl-posts_paginate, #tbl-posts_filter{
		float: right;
	}
	.select2{
		width: 100% !important;
	}
	.select2-container--default .select2-selection--single{
		height: 38px;
	}
	.select2-container--default .select2-selection--multiple .select2-selection__choice{
		color:#000;
	}
	.list-permissions{
		-webkit-column-count: 3;
		-moz-column-count: 3;
		column-count: 3;
	}
</style>
@endsection
@section('content')
<div class="card shadow mb-4">
	<div class="card-header py-3">
		@can('create user')
		<a type="button" data-target="#modal-create" data-toggle="modal" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Tambah User</a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		@endcan
		<h6 class="card-title float-right">DataTable User</h6>
	</div>
	<div class="card-body">
		<table id="tbl-user" class="table table-bordered table-hover dataTable">
			<thead>
				<th width="5%">No</th>
				<th>User</th>
				<th>Email</th>
				<th>Hak Akses</th>
				@canany(['edit user', 'delete user', 'reset password user'])
				<th width="10%">Action</th>
				@endcan
			</thead>
			<tbody>
				@foreach($users as $user)
				<tr>
					<td>{{$loop->iteration}}</td>
					<td>{{$user->name}}</td>
					<td>{{$user->email}}</td>
					@if($user->roles->count() > 0)
					<td>
						<ul style="padding-left: 15px;">
							@foreach($user->roles as $role)
							<li>
								<b>{{ucwords($role->name)}}</b>:<br> 
								@foreach($role->permissions as $permission)
								<span class="badge badge-secondary mr-2 mt-2 p-1">{{ucwords($permission->name)}}</span>
								@endforeach
							</li>
							@endforeach
						</ul>
					</td>
					@else
					<td><center><i>No Item</i></center></td>
					@endif
					@canany(['edit user', 'delete user', 'reset password user'])
					<td class="text-nowrap">
						@can('edit user')
						<button class="btn btn-sm btn-warning" data-id="{{$user->id}}" data-name="{{$user->name}}" data-email="{{$user->email}}" data-roles="{{$user->roles->pluck('name')->toJson()}}" onclick="modalEdit(this)"><i class="fa fa-edit"></i></button>
						&nbsp;
						@endcan
						@can('reset password user')
						<button class="btn btn-sm btn-primary" data-id="{{$user->id}}" data-name="{{$user->name}}" onclick="modalReset(this)"><i class="fa fa-key"></i></button>
						&nbsp;
						@endcan
						@can('delete user')
						<button class="btn btn-sm btn-danger" data-id="{{$user->id}}" data-name="{{$user->name}}" onclick="modalDelete(this)"><i class="fa fa-trash"></i></button>
						@endcan
					</td>
					@endcan
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>

@can('create user')
<div class="modal fade" id="modal-create" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form method="POST" action="{{route('dashboard.user.store')}}">
				@csrf
				<div class="modal-header bg-primary">
					<h5 class="modal-title text-white">Tambah User</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" name="password" minlength="6" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Confirm Password</label>
						<input type="password" minlength="6" name="repassword" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Roles</label>
						<select class="form-control select2" multiple name="roles[]" onchange="getPermission(this)" required>
							@foreach($roles as $role)
							<option value="{{$role->name}}" data-permissions="{{$role->permissions->pluck('name')->toJson()}}">{{ucwords($role->name)}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group d-none" id="form-permissions">
						<label>Permissions</label>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('edit user')
<div class="modal fade" id="modal-edit" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('PUT')
				<div class="modal-header bg-warning">
					<h5 class="modal-title text-white">Edit User</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Roles</label>
						<select class="form-control select2" multiple name="roles[]" onchange="getPermission(this)" required>
							@foreach($roles as $role)
							<option value="{{$role->name}}" data-permissions="{{$role->permissions->pluck('name')->toJson()}}">{{ucwords($role->name)}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group d-none" id="form-permissions">
						<label>Permissions</label>
					</div>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-warning">Upadte</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('reset password user')
<div class="modal fade" id="modal-reset" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('PUT')
				<div class="modal-header bg-primary">
					<h5 class="modal-title text-white">Reset Password User</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Password</label>
						<input type="password" name="password" minlength="6" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Confirm Password</label>
						<input type="password" name="repassword" minlength="6" class="form-control" autocomplete="off" required>
					</div>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Upadte</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('delete user')
<div class="modal fade" id="modal-delete" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('DELETE')
				<div class="modal-header bg-danger">
					<h5 class="modal-title text-white">Hapus User</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Are you sure delete user <b id="modal-delete-user"></b></p>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-danger">Delete</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@endsection
@push('js')
<script src="{{asset('vendor/select2/select2.min.js')}}"></script>
<script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
<script type="text/javascript">
	$(document).ready( function () {
		$('#tbl-user').DataTable();
		$('.select2').select2();
	});

	@canany(['create user', 'edit user'])
	function getPermission(self)
	{
		var modal   = $(self).parents('.modal');
		var results = [];
		var data = $(self).find("option:selected");
		if (data.length > 0) {
			data.each(function(el){
				var roles = $(this).data('permissions');
				roles.forEach(function(role){
					results.push(role);
				});
			});
			results  = results.filter(onlyUnique);
			var html = "<ul class='list-permissions'>";
			results.forEach(function(permission){
				html += "<li>"+permission+"</li>"
			});
			html += "</ul";
			modal.find('#form-permissions').removeClass('d-none');
			modal.find('#form-permissions').empty();
			modal.find('#form-permissions').append(html);
		}else{
			modal.find('#form-permissions').addClass('d-none');
			modal.find('ul.list-permissions').remove();
		}
	}
	
	function onlyUnique(value, index, self) {
		return self.indexOf(value) === index;
	}
	@endcan


	@can('edit users')
	function modalEdit(self)
	{
		var id    = $(self).attr('data-id');
		var name  = $(self).attr('data-name');
		var email = $(self).attr('data-email');
		var roles = JSON.parse($(self).attr('data-roles'));
		var modal = $('#modal-edit');
		var url   = '{{ route("dashboard.user.update", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.find('input[name="name"]').val(name);
		modal.find('input[name="email"]').val(email);
		modal.find('select[name="roles[]"]').val(roles).change();
		modal.modal('show');
	}
	@endcan

	@can('reset password users')
	function modalReset(self)
	{
		var id    = $(self).attr('data-id');
		var name  = $(self).attr('data-name');
		var modal = $('#modal-reset');
		var url   = '{{ route("dashboard.user.reset-password", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.modal('show');
	}
	@endcan

	@can('delete users')
	function modalDelete(self)
	{
		var id    = $(self).attr('data-id');
		var modal = $('#modal-delete');
		var url   = '{{ route("dashboard.user.destroy", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.find('#modal-delete-user').html('('+$(self).attr('data-name')+')');
		modal.modal('show');
	}
	@endcan
</script>
@endpush